const banksList = [
  "State Bank of India (SBI)",
  "Bank of Baroda (BOB)",
  "Punjab National Bank (PNB)",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "Central Bank of India",
  "Indian Bank",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "IDFC FIRST Bank",
  "Yes Bank",
  "Federal Bank",
  "RBL Bank",
  "South Indian Bank",
  "Karnataka Bank",
  "Karur Vysya Bank",
  "City Union Bank",
  "Dhanlaxmi Bank",
  "CSB Bank",
  "Tamilnad Mercantile Bank",
  "DBS Bank India",
  "DCB Bank",
  "Bandhan Bank",
  "IDBI Bank",
  "AU Small Finance Bank",
  "Equitas Small Finance Bank",
  "Ujjivan Small Finance Bank",
  "Jana Small Finance Bank",
  "Utkarsh Small Finance Bank",
  "Suryoday Small Finance Bank",
  "ESAF Small Finance Bank",
  "HSBC",
  "Standard Chartered Bank",
  "Deutsche Bank",
  "SBM Bank India",
  "The Kalupur Commercial Co-operative Bank"
];

exports.getBanks = (req, res) => {
  res.status(200).json({
    success: true,
    data: banksList
  });
};
